### ISSUE TITLE
Needs package.json file.

### ISSUE THREAD

**Issue by chief10** [artemsheludko/flexible-jekyll#1]
Beautiful theme; thanks for sharing it!

Is there a `package.json` file for this?

**Comment by artemsheludko** [comment]
Thank you! Yes of course, here's the link [package.json](https://github.com/artemsheludko/Jekyll-Gulp-Sass-Autoprefixer-Imagemin-BrowserSync/blob/master/package.json)

**Comment by kalenjohnson** [comment]
Hi, just curious why this is not in the repo and gitignored.

**Comment by artemsheludko** [comment]
Yes, indeed it was my mistake. I fixed it. Thanks, guys!

**Comment by DaleMatthews** [comment]
Love your themes, but it'd be very useful to see the target jekyll version in your repos. Most jekyll themes have a `Gemfile.lock` for that reason.

**Comment by artemsheludko** [comment]
You are right, I will consider this. Thank you!
