### ISSUE TITLE
Two files not found

### ISSUE THREAD

**Issue by Jie-Cheng** [artemsheludko/flexible-jekyll#30]
Two files seem to be missing from the repository which result in the following errors after starting the server:

> `/flexible-jekyll/assets/img/favicon/apple-touch-icon-114x114.png' not found.

> `/flexible-jekyll/assets/img/favicon/favicon.ico' not found.

**Comment by jamesddelaney** [comment]
@artemsheludko @Jie-Cheng - can this issue now be closed?

**Comment by artemsheludko** [comment]
@jamesddelaney Yes, thanks again!
