### ISSUE TITLE
Photo Credits

### ISSUE THREAD

**Issue by diazgilberto** [artemsheludko/flexible-jekyll#31]
I don't know if the feature exists or not...
I'm using photos from Flickr with "All creative commons" license in my posts and I would like to include the author of the picture or in some way give credit to the person who shot the photograph. Could be a note just below the image or on top of the image on one of the bottom corners. If you can point me in the right direction I'll appreciated.

**Comment by artemsheludko** [comment]
@diazgilberto Added a feature. Now you can leave a signature under the pictures. I hope it will be useful. For example,
![screen shot 2018-05-31 at 5 49 53 pm](https://user-images.githubusercontent.com/22279513/40790050-899d033a-64fc-11e8-9e4e-efe9688d9b71.png)

![screen shot 2018-05-31 at 5 50 15 pm](https://user-images.githubusercontent.com/22279513/40790088-a68d28d0-64fc-11e8-8ba9-25094fa9ff7d.png)

**Comment by diazgilberto** [comment]
Well, I normally don't add images to the post, but the image I'm talking about is the one that get pulled from the `img` property in the header.

**Comment by artemsheludko** [comment]
@diazgilberto Ok, done.

![screen shot 2018-06-02 at 11 14 04 am](https://user-images.githubusercontent.com/22279513/40872440-fa63f10e-6656-11e8-9ee0-37b830ec355b.png)

![screen shot 2018-06-02 at 11 13 49 am](https://user-images.githubusercontent.com/22279513/40872443-00a1adae-6657-11e8-9606-94fd7a87e35f.png)

**Comment by diazgilberto** [comment]
Thanks, that was quick. I clone the repo and copied the folder `assets/css`, and the file `_layout/post.html` to my project. Then I added a `fig-caption` to one of my posts, then `jekyll build` and push to gh-pages. After a while I went to my blog to see the change but the credit doesn't show. I inspected the element...

![figcaption-position](https://user-images.githubusercontent.com/9165819/40883160-55041516-66bc-11e8-8766-e879e63a863a.png)

**Comment by artemsheludko** [comment]
@diazgilberto It was probably necessary to wait a little. Already everything works.

![estados unidos descubierto en la biblia - el ultimo tiempo - google chrome](https://user-images.githubusercontent.com/22279513/40883705-36b653da-670c-11e8-8b3b-ac24b5bbb94e.jpg)

**Comment by diazgilberto** [comment]
It took longer than before. Thank you so much!
Closing the issue.

**Comment by artemsheludko** [comment]
@diazgilberto You are welcome!

**Comment by diazgilberto** [comment]
I'm trying to change `font-weight` for the `<figcaption>`. Mi thought is that if I add `font-weight: 300;` in the `_post-page.scss` like so...

```
  figcaption {
    position: absolute;
    top: 20px;
    right: 20px;
    padding-left: 20px;
    color: rgba(255, 255, 255, 0.7);
    text-shadow: 0 1px 5px rgba(0, 0, 0, 0.2);
    font-weight: 700;
    text-transform: uppercase;
    font-size: 10px;
    font-weight: 300;
  }
```

and in the `post.html` refactor the line to `<figcaption>Photo By <b>{{page.fig-caption}}</b></figcaption>`, after I run `jekyll build`, jekyll will compile my scss to css. I don't know if my assumption is wrong or not. Can you point me to the right direction? If you like the change I can do a `PR`.
