### ISSUE TITLE
Providing no image leaves an empty space

### ISSUE THREAD

**Issue by toubou91** [artemsheludko/flexible-jekyll#4]
Hi,

nice effort 👍 

Maybe I haven't taken enough time to read the project, but the image of a post is meant to be an optional attribute. However, if I don't provide any image, I end up with a post that looks like corrupted to the user:

![screen shot 2017-10-14 at 02 10 58](https://user-images.githubusercontent.com/5684688/31570552-2f80681e-b085-11e7-99a3-3c72110163ae.png)

Am I missing something or is it indeed a bug?

Regards,
Thodoris

**Comment by artemsheludko** [comment]
Yes, indeed you are right. I fixed it. Thank you!

**Comment by toubou91** [comment]
Perfect fix, helped me understand a lot of things, thanks!

**Comment by artemsheludko** [comment]
You're welcome! If you have any further questions, contact me.

**Comment by toubou91** [comment]
Will do, thank you!
