### ISSUE TITLE
Thumbnail's text is displaying author's description

### ISSUE THREAD

**Issue by toubou91** [artemsheludko/flexible-jekyll#5]
Hello,

wouldn't it be nice if thumbnail's text displayed the respective post's first few lines of text (, instead of author's description) ?

![screen shot 2017-10-15 at 02 31 27](https://user-images.githubusercontent.com/5684688/31580483-16544f3c-b151-11e7-94e8-18eed7968223.png)

<em>If you want, I can pick this up, if you provide a hint/tip.</em>
Regards,
Thodoris

**Comment by artemsheludko** [comment]
If I understood you correctly. This should help 
![screen shot 2017-10-15 at 1 49 06 pm](https://user-images.githubusercontent.com/22279513/31584078-b5527fba-b1af-11e7-9d98-9be9c2cccf52.png)

**Comment by toubou91** [comment]
Cool, now I got the entire concept, thanks a lot!
