### ISSUE TITLE
markdown doesn't work on _config.yml

### ISSUE THREAD

**Issue by toubou91** [artemsheludko/flexible-jekyll#6]
Hello,

I know, this is not meant to be the proper way of using jekyll, but please let me explain the following scenario:
As an author, I would like to have a link displayed in my author's description (`about-author` property in `_config.yml`; example: `[Thodoris](link/to/site)` ).

Of course, this is out of the scope of this project, since it is more global, but I would like to first hear your opinion (, since I'm just a newbie with jekyll), before escalating this to the official project (also because I'm not sure whether the main project -jekyll/jekyll- is the most relevant one to this case).

Regards,
Thodoris

**Comment by artemsheludko** [comment]
Unfortunately, markdown doesn't work on `_config.yml`. There is one way to add a link to the beginning or the end of the description. There are other ways, but this is the simplest. For example 
![screen shot 2017-10-15 at 12 24 23 pm](https://user-images.githubusercontent.com/22279513/31583428-530bc178-b1a4-11e7-8040-303e619faab8.png)

**Comment by toubou91** [comment]
Cool, thanks!
