### ISSUE TITLE
Is there any way to have a proper thumbnail for twitter?

### ISSUE THREAD

**Issue by thodorisbais** [artemsheludko/flexible-jekyll#7]
Right now it is displayed like this, which I am not that fond of
![screen shot 2017-10-20 at 21 55 25](https://user-images.githubusercontent.com/5684688/31839491-97a28416-b5e1-11e7-91bb-c5b2efcbf193.png)

**Comment by artemsheludko** [comment]
To be honest, I do not know. I never thought about it. If I find a solution I will write to you.

**Comment by toubou91** [comment]
Yes, I believe it would be a great step for this project to also support such a feature.
Let me know if you need any help.

**Comment by artemsheludko** [comment]
Okay, thanks!

**Comment by kentonh** [comment]
This should probably be done through [Twitter cards](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started) and if that's being added, it might be good to add [Facebook Open Graph data](https://developers.facebook.com/docs/sharing/webmasters)

**Comment by toubou91** [comment]
I will take a look until EOD and close the issue if it is the case!
Thanks a lot @kentonh anyways!

**Comment by toubou91** [comment]
Was a bit late (Friday hah), will do it today.

**Comment by toubou91** [comment]
Solution looks good, but how could we enhance it so that the image of the post is being displayed in the thumbnail? @kentonh 
![screen shot 2017-11-11 at 22 04 59](https://user-images.githubusercontent.com/5684688/32693509-6bed18f2-c72c-11e7-8a6c-a182b1491770.png)

**Comment by kentonh** [comment]
I️ think I️ need to update the image url in the code. It’s working on my local fork, but it must be correct for file structure.

**Comment by toubou91** [comment]
@kentonh since I noticed it was merged, I thought it would be "plug'n'play", but of course, the project itself is mostly specific to Artem's details.
However, I'm still facing some trouble. Could you please help? https://github.com/toubou91/toubou91.github.io

**Comment by kentonh** [comment]
@artemsheludko I've made a new PR #12 to clean up the implementation.

**Comment by kentonh** [comment]
@toubou91 I've made a new PR that removes the need to edit `_includes/head.html` for your specific site implementation. Once merged, you should be able to update and all social graph and twitter card meta information will be determined via Jekyll's `_config.yml` file

**Comment by artemsheludko** [comment]
@kentonh Thank you for your time. Good job!

**Comment by toubou91** [comment]
Gonna check in a bit, thanks a lot!

**Comment by toubou91** [comment]
@kentonh for facebook and linkedin it seems to work fine, but for twitter I keep having the same issue, as depicted above.

**Comment by toubou91** [comment]
Wow @artemsheludko , 29 days ago I left this repo with less than 90 forks, good job man 👍 .
Sorry for my inactivity guys, other stuff kept me away from testing this feature.
Hopefully, I will find some time during this weekend.

**Comment by artemsheludko** [comment]
@toubou91 Thank you for your active participation in the project.

**Comment by toubou91** [comment]
Still the same. It doesn't work for twitter. I have merged the latest changes, but of course something might have gone wrong again. Could you please [check](https://github.com/toubou91/toubou91.github.io)?
_I also lost the previously working functionality of jemoji_ .

**Comment by gutblog** [comment]
I think I just solved this issue with my pull request: https://github.com/artemsheludko/flexible-jekyll/pull/24

Example tweet with card: https://twitter.com/gutfeelingblog/status/962733501429592064

**Comment by thodorisbais** [comment]
I just synced my fork, but it still doesn't work for Twitter:

![screen shot 2018-02-25 at 21 32 17](https://user-images.githubusercontent.com/5684688/36646114-729c04e8-1a73-11e8-8ec8-7fb175443453.png)

**Comment by gutblog** [comment]
@thodorisbais Please try your article's URL in https://cards-dev.twitter.com/validator and see if it shows you a valid card. AFAIK The validator will pull the most recent version of your site, so if you get a valid card using the validator, it should propagate to the rest of Twitter within a few minutes.

Otherwise, we might be able to help if you post the error from the Twitter validator, along with the final HTML meta tag snippet that it is reading in your site to try to construct the card.

**Comment by thodorisbais** [comment]
@gutblog the card is said to be properly validated from the site:

![screen shot 2018-02-25 at 22 56 57](https://user-images.githubusercontent.com/5684688/36647051-faac1024-1a7f-11e8-886d-a3455d2a7761.png)

Am I configuring the post images in a wrong way maybe in my [fork](https://github.com/thodorisbais/thodorisbais.github.io/blob/master/_posts/2018-02-25-how-to-sync-a-fork.markdown)?

**Comment by gutblog** [comment]
@thodorisbais Your final, compiled code:

    <meta name="twitter:image:src" content="/assets/img/git-logo.png">

Twitter images need to be absolute URLs if I am not mistaken (they must include your website's domain name). The culprit is your `_config.yml` file, which does not have your site's URL defined. Change your `_config.yml` line 6 from:

    url: "" # the base hostname & protocol for your site, e.g. http://example.com

to

    url: "https://thodorisbais.github.io" # the base hostname & protocol for your site, e.g. http://example.com

and your Twitter photo should start working!

**Comment by thodorisbais** [comment]
OH. MY. GAD.
We learned something today!
Many thanks @gutblog 😃 
(Finally) closing (after 4 months)

**Comment by ricoms** [comment]
I'm trying to solve this issue nowadays, and I can't find how. I included in `head.hml`:

`<meta name="twitter:card" content="{{ '/assets/img/twitter-card.png' | relative_url }}" />`

and the image is available at that local path, although testing on [twitter-validator](https://cards-dev.twitter.com/validator) I get this:

```
INFO:  Page fetched successfully
INFO:  14 metatags were found
INFO:  twitter:card = /assets/img/twitter-card.png tag found
ERROR: Invalid card name (Card error)
```

**Comment by ricoms** [comment]
I finally understood the problem, `twitter:image` only accepts absolute path to the image. 

[Here](https://github.com/multimediaeval/multimediaeval.github.io/issues/28) is the solution.
