### ISSUE TITLE
My site couldn't display the layout

### ISSUE THREAD

**Issue by Marina-Ma** [artemsheludko/flexible-jekyll#8]
I cloned your theme, but it could not work. 
If you have time, please have a look at my website: https://marina-ma.github.io/

**Comment by artemsheludko** [comment]
You need to remove the subpath in the `baseurl`. This should help.
![screen shot 2017-10-26 at 12 17 54 pm](https://user-images.githubusercontent.com/22279513/32045649-7bc9aaaa-ba49-11e7-8ab9-3545ab15b4a3.png)

**Comment by Marina-Ma** [comment]
Yes, it works. Thanks very much

**Comment by artemsheludko** [comment]
You're welcome!

**Comment by dandymilton** [comment]
for: user.
if you try to change your minima theme to flexible-jekyll, delete all of your old-file.
