### ISSUE TITLE
Some text format in markdown cannot dispaly in the webpage

### ISSUE THREAD

**Issue by Marina-Ma** [artemsheludko/flexible-jekyll#9]
Hello,
I really love your theme and thanks for sharing with us. Today I encunted a problem. Hope you can help me.

Some text format in markdown cannot display in the webpage (showed in the picture) while it can do in the GitHub. 

![problem](https://user-images.githubusercontent.com/33084062/32141010-9465982c-bcaf-11e7-94e4-1f66ec0833d1.png)

* GitHub
https://github.com/Marina-Ma/Marina-Ma.github.io/blob/master/_posts/2017-10-26-Markdown-Writing.md

* webpage 
https://marina-ma.github.io/Markdown-Writing/

Thanks

Marina

**Comment by artemsheludko** [comment]
Hi, thank you! You need to connect support for emoji. You can do it this way 
![screen shot 2017-10-29 at 1 19 44 pm](https://user-images.githubusercontent.com/22279513/32143039-19d40e0c-bcac-11e7-8f86-e644da808817.png)
![screen shot 2017-10-29 at 1 23 57 pm](https://user-images.githubusercontent.com/22279513/32143069-836597e6-bcac-11e7-9509-afa52ee98df3.png)

Also, see the documentation for this link [Emoji on GitHub Pages](https://help.github.com/articles/emoji-on-github-pages/)

**Comment by Marina-Ma** [comment]
Thanks for your help. the emoji can display now :smile:  I just learn Jekyll from scratch and have encountered so many problems. 

There are still two problems left (see the picture). Could you please help me?  

![default](https://user-images.githubusercontent.com/33084062/32144486-9a6330f0-bcf4-11e7-9f63-299b23ccec17.PNG)

**Comment by artemsheludko** [comment]
For pictures, you need to add the full path, at the end of the link `?raw=true`. With the tables the problem is solved, I added the styles, now everything will work. Example: 
![screen shot 2017-10-29 at 4 56 54 pm](https://user-images.githubusercontent.com/22279513/32145204-358d007e-bccd-11e7-808b-a3efa7c0789e.png)

**Comment by Marina-Ma** [comment]
Every problem is solved. Thanks so much.
